import React from "react";
export async function llenarcolumns() {
	return columnsFill();
}

function columnsFill() {
	return new Promise(function (resolve) {
		resolve([
			// {
			// 	headerName: "Transporte(ID)",
			// 	field: "id",
			// 	editable: "never",
			// 	order: true,
			// 	headerClassName: "encabcolumns",
			// },
			{
				headerName: "Descripción",
				field: "TransporteDesc",
				order: true,
				width: 250,
				editable: true,
				required: true,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Teléfono ",
				field: "TransporteTel1",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Teléfono ",
				field: "TransporteTel2",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "WhatsApp ",
				field: "TransporteWA",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Mail ",
				field: "TransporteMail",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Domicilio ",
				field: "TransporteDom",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Localidad ",
				field: "TransporteLoc",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Destino ",
				field: "TransporteDestino",
				width: 250,
				editable: true,
				required: true,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
			{
				headerName: "Observaciones ",
				field: "TransporteObser",
				width: 250,
				editable: true,
				required: false,
				maxLength: 45,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: "encabcolumns",
			},
		]);
	});
}
