import { leeTipoClien } from "./LeeTipoClien";
import estilotabla from "../../../Styles/Tabla.module.css";

export async function llenarcolumns() {
	const tipoclien = await leeTipoClien();

	return columnsFill(tipoclien);
}

function columnsFill(tipoclien) {
	return new Promise(function (resolve) {
		resolve([
			// {
			// 	headerName: "Cód",
			// 	field: "id",
			// 	width: 25,
			// 	xs: 4,
			// 	editable: false,
			// 	headerClassName: "encabcolumns",
			// },
			{
				headerName: "Descripción",
				field: "ClientesDesc",
				order: true,
				width: 250,
				editable: true,
				required: true,
				maxLength: 145,
				pattern: /^/,
				xs: 8,
				placeholder: "_________________",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Domicilio",
				field: "ClientesDomicilio",
				width: 230,
				defaultValue: "",
				editable: true,
				required: true,
				type: "text",
				maxLength: 145,
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "CodPos",
				field: "ClientesCodPos",
				width: 50,
				editable: true,
				type: "text",
				maxLength: 15,
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Loc",
				field: "ClientesLoc",
				width: 200,
				maxLength: 145,
				editable: true,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Pcia",
				field: "ClientesPcia",
				width: 150,
				editable: true,
				maxLength: 145,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Tel-WA",
				field: "ClientesTel",
				width: 250,
				type: "text",
				editable: true,
				required: true,
				maxLength: 20,
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "IVA",
				field: "ClientesIVA",
				width: 50,
				editable: true,
				maxLength: 1,
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "CUIT",
				field: "ClientesCUIT",
				width: 120,
				editable: true,
				required: true,
				color: "secondary",
				maxLength: 13,
				type: "text",
				pattern: /^[0-9]{0,2}-[0-9]{0,8}-[0-9]{1,1}$/,
				placeholder: "99-99999999-9",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Mail",
				field: "ClientesMail",
				width: 250,
				editable: true,
				maxLength: 145,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Tipo",
				field: "ClientesTipo",
				type: "singleSelect",
				width: 150,
				maxLength: 1,
				valueOptions: tipoclien,
				editable: true,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Contacto",
				field: "ClientesContacto",
				width: 150,
				editable: true,
				maxLength: 145,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Categoría",
				field: "ClientesCategoria",
				width: 50,
				maxLength: 45,
				editable: true,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Observación",
				field: "ClientesObserv1",
				width: 350,
				editable: true,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Observación",
				field: "ClientesObserv2",
				width: 350,
				editable: true,
				type: "text",
				//xs: 4,
				headerClassName: estilotabla.encabcolumns,
			},
			// {
			// 	headerName: "Fecha",
			// 	field: "ClientesFecha",
			// 	//width: 150,
			// 	type: "Date",
			// 	editable: true,
			// 	//xs: 4,
			// 	headerClassName: estilotabla.encabcolumns,
			// },
		]);
	});
}
