import { leeStkRubro } from "../StkItems/leeStkRubro";
import estilotabla from "../../../Styles/Tabla.module.css";
export async function llenarcolumns() {
	const stkRubros = await leeStkRubro();
	return columnsFill(stkRubros);
}
function columnsFill(stkRubros) {
	return new Promise(function (resolve) {
		resolve([
			// {
			// 	headerName: "Presup.Tipo(ID)",
			// 	field: "id",
			// 	editable: "never",
			// 	order: true,
			// 	headerClassName: "encabcolumns",
			// },+
			{
				headerName: "Descripción",
				field: "PresupConfTipoDesc",
				order: true,
				width: 200,
				editable: true,
				required: true,
				maxLength: 100,
				pattern: /^/,
				xs: 8,
				placeholder:
					"__________________________________________________________",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Rubro Abr",
				field: "PresupConfTipoRubro",
				type: "singleSelect",
				valueOptions: stkRubros,
				order: true,
				width: 200,
				editable: true,
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Cantidad",
				field: "PresupConfTipoCant",
				order: false,
				width: 150,
				type: "number",
				editable: true,
				required: false,
				maxLength: 5,
				pattern: /^/,
				xs: 8,
				placeholder: "______",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Es m2 S/N",
				field: "PresupConfTipoM2",
				order: true,
				width: 150,
				editable: true,
				required: true,
				maxLength: 1,
				pattern: /^/,
				xs: 8,
				placeholder: "____",
				headerClassName: estilotabla.encabcolumns,
			},

			{
				headerName: "Es Anexo?",
				field: "PresupConfTipoAnexo",
				order: true,
				width: 150,
				editable: true,
				required: true,
				maxLength: 1,
				pattern: /^/,
				xs: 8,
				placeholder: "____",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Pide Largo?",
				field: "PresupConfTipoLargo",
				order: true,
				width: 150,
				editable: true,
				required: true,
				maxLength: 1,
				pattern: /^/,
				xs: 8,
				placeholder: "____",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Pide Ancho?",
				field: "PresupConfTipoAncho",
				order: true,
				width: 150,
				editable: true,
				required: true,
				maxLength: 1,
				pattern: /^/,
				xs: 8,
				placeholder: "____",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Imprime?",
				field: "PresupConfTipoImprime",
				order: true,
				width: 150,
				editable: true,
				required: true,
				maxLength: 1,
				pattern: /^/,
				xs: 8,
				placeholder: "____",
				headerClassName: estilotabla.encabcolumns,
			},
			{
				headerName: "Min. MOT",
				field: "PresupConfTipoMinMOT",
				order: false,
				width: 150,
				type: "number",
				editable: true,
				required: false,
				maxLength: 5,
				pattern: /^/,
				xs: 8,
				placeholder: "______",
				headerClassName: estilotabla.encabcolumns,
			},
		]);
	});
}
